### ISSUE TITLE
installing new template

### ISSUE THREAD

**Issue by nicolasdb** [nicolasdb/nicolasdb.github.io#10]
So, I found this one:
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

- I forked as they ask and enabled it in the settings.
- I have now a clean new website @ https://nicolasdb.github.io/minimal-mistakes/
- I have cloned it locally and after creating a new branch on **nicolasdb.github.io**, I want to copy/past what I need. I'll follow the guide. (first, i zip the folder somewhere, just to be safe)
- houla, carrefull to NOT copy/paste .git folder. It will mess with versionning.

**Comment by nicolasdb** [comment]
![image](https://user-images.githubusercontent.com/12049360/32375607-8f6e40c0-c0a2-11e7-8069-e7be0d3350aa.png)

**Comment by nicolasdb** [comment]
# settings
## _config.yml
## _data/navigation.yml
## Pages
```
---
title: "Splash Page"
layout: splash
permalink: /splash-page/
---
```
title: to overwrite title from _config.yml
layout: to choose which layout to use, from /_layouts
permalink: to force specific link to use elsewhere

## Posts

**Comment by nicolasdb** [comment]
to add a custom link under your profil User, with youtube, facebook, github, and shit. 

Just look here >_includes/author-profile.html
and add your new link into >_includes/author-profile-custom-links.html

like this:
 ```
 <li>
    <a href="https://vimeo.com/{{ author.vine }}" itemprop="sameAs">
      <i class="fa fa-fw fa-vimeo" aria-hidden="true"></i> Vimeo
    </a>
  </li>
```

**Comment by nicolasdb** [comment]
From fresh.... 
- setup ghpages on master
- delete noneed files
- add _posts and _pages from doc origin
- add this as explain

> Add remote_theme: "mmistakes/minimal-mistakes" to your _config.yml file.
> Then add jekyll-remote-theme to the plugins (previously gems) array in your _config.yml file like so:
 ```
plugins:
   - jekyll-remote-theme
whitelist:
   - jekyll-remote-theme
```

+ add to config.yml after #defaults
```
# _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true

```
ok nice, it's working.

**Comment by nicolasdb** [comment]
next:
change homepage with new index.html.
I switch to .md file
add "title : Nicolas de Barquin" as yaml value
and change the picture with a link in \assets

ha, and also, I change links into the navigation.yml to 
```
# main links
main:
  # - title: "Quick-Start Guide"
  #   url: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
   - title: "About"
     url: /about/
   - title: "Sample Posts"
     url: /year-archive/
  # - title: "Sample Collections"
  #   url: /collection-archive/
  # - title: "Sitemap"
#   url: /sitemap/
```
just un# or # what you want to see and adjust link to the permalink use in the "yaml" setting of your page (in /_pages)

**Comment by nicolasdb** [comment]
getting back on _config.yml

_**words_per_minutes?** 
Reading speed, test yours on http://www.readingsoft.com/
ou en français sur https://lecturerapideblog.com/outils/test-vitesse-lecture/_

**Comment by nicolasdb** [comment]
erreur 404,
ha good, it's customizable too, lol

and for posts, just add and tweek
```
---
title: "Foam cutting"
excerpt_separator: "<!--more-->"
categories:
  - Tuto
tags:
  - Post Formats
  - readability
  - standard
---
```

before your content.

**Comment by nicolasdb** [comment]
Proposition d'agenda simple pour OF

xxx | lundi | mardi | mercredi | jeudi | vendredi | samedi | dimanche 
:--- |  :---: |  :----: | :--------: | :----: | :--------: | :------: | :---:
matin | nico |  | nico | nico | 
aprem |  |  | nico |  | 
soir |

**Comment by nicolasdb** [comment]
Adding Main link to other repo, for ex. Lootcrate readme.

# main links
main:
   - title: "Lootcrate"
url: https://nicolasdb.github.io/lootcrate/blob/master/README.md

**Comment by nicolasdb** [comment]
lead for using MD files from other Repo
https://stackoverflow.com/questions/33113945/can-jekyll-use-a-config-file-from-a-different-repo

**Comment by nicolasdb** [comment]
to add another folder for something. 
Like to add _portfolio

create file and add this in _config.yml under #defaults
```
# _portfolio
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
```
